// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM2nIAq828mRuuNYi90-P_YIpz8En9pJ8',
    appId: '1:337837807270:web:bfa5d791e770cf8fc94667',
    messagingSenderId: '337837807270',
    projectId: 'evently-app-dff85',
    authDomain: 'evently-app-dff85.firebaseapp.com',
    storageBucket: 'evently-app-dff85.firebasestorage.app',
    measurementId: 'G-B9XPR68N0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNQPtWU71vZXil_pJgHrBnoAsxZ1O0KGs',
    appId: '1:337837807270:android:8afc3e53ff6f082fc94667',
    messagingSenderId: '337837807270',
    projectId: 'evently-app-dff85',
    storageBucket: 'evently-app-dff85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDaxchMfM4a4OTOMB2SET4Jg7A3p7I9Q8',
    appId: '1:337837807270:ios:27f9812d7c9009abc94667',
    messagingSenderId: '337837807270',
    projectId: 'evently-app-dff85',
    storageBucket: 'evently-app-dff85.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDaxchMfM4a4OTOMB2SET4Jg7A3p7I9Q8',
    appId: '1:337837807270:ios:27f9812d7c9009abc94667',
    messagingSenderId: '337837807270',
    projectId: 'evently-app-dff85',
    storageBucket: 'evently-app-dff85.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM2nIAq828mRuuNYi90-P_YIpz8En9pJ8',
    appId: '1:337837807270:web:d134fc3acc5f7603c94667',
    messagingSenderId: '337837807270',
    projectId: 'evently-app-dff85',
    authDomain: 'evently-app-dff85.firebaseapp.com',
    storageBucket: 'evently-app-dff85.firebasestorage.app',
    measurementId: 'G-G1VNHDV9PB',
  );
}
